### ISSUE TITLE
why

### ISSUE THREAD

**Issue by java67** [DerpFest-11/packages_apps_SettingsIntelligence#1]
error: packages/apps/SettingsIntelligence/Android.bp:15:1: module "SettingsIntel
ligence" variant "android_common": sdk_version: sdk_version must have a value wh
en the module is located at vendor or product(only if PRODUCT_ENFORCE_PRODUCT_PA
RTITION_INTERFACE is set).

**Comment by NurKeinNeid** [comment]
As explained on Telegram, this repo is not used at all. I will remove this repo for you tonight. Maybe its more clear for you then.
